name: Build Wheels and Publish

on:
  release:
    types: [published]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          EIGEN3_INCLUDE_DIR: ${{ github.workspace }}/vendor/eigen3
          CIBW_BUILD: "cp39* cp310* cp311* cp312* cp313*"
          CIBW_SKIP: ${{ matrix.os == 'ubuntu-latest' && "cp36-* cp37-* cp38-* cp39-manylinux_i686* cp310-manylinux_i686* cp311-manylinux_i686* cp312-manylinux_i686* cp313-manylinux_i686*" || "" }}
          CIBW_BEFORE_BUILD: ${{ matrix.os == 'ubuntu-latest' && "yum -y install eigen3-devel || true" || "" }}
        run: cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse

  pypi_publish:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Create directory for combined wheels
        run: mkdir -p combined_wheels

      - name: Download wheels artifact from Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: combined_wheels

      - name: Download wheels artifact from macOS
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: combined_wheels

      - name: Download wheels artifact from Windows
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: combined_wheels

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: combined_wheels
