name: learner-py

on:
  push:
    branches: ["build-wheels-branch"]

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set OS-specific environment variables
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            echo "CIBW_MANYLINUX_X86_64_IMAGE=manylinux_2_28" >> $GITHUB_ENV
            echo "CIBW_BEFORE_BUILD=yum -y install eigen3-devel || true" >> $GITHUB_ENV
            echo "CIBW_SKIP=cp39-manylinux_i686* cp310-manylinux_i686* cp311-manylinux_i686* cp312-manylinux_i686* cp313-manylinux_i686*" >> $GITHUB_ENV
          else
            echo "CIBW_MANYLINUX_X86_64_IMAGE=" >> $GITHUB_ENV
            echo "CIBW_BEFORE_BUILD=" >> $GITHUB_ENV
            echo "CIBW_SKIP=" >> $GITHUB_ENV
          fi

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          EIGEN3_INCLUDE_DIR: "${{ github.workspace }}/vendor/eigen3"
          CIBW_BUILD: "cp39* cp310* cp311* cp312* cp313*"
        run: cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse

  pypi-publish:
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Create combined wheels directory
        run: mkdir -p combined_wheels

      - name: Download wheels artifact from Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: combined_wheels

      - name: Download wheels artifact from macOS
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: combined_wheels

      - name: Download wheels artifact from Windows
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: combined_wheels

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: combined_wheels
