name: learner-py

on:
  release:
    types: [published]

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List host Eigen directories
        run: |
          echo "Listing /usr/include/eigen3:"
          ls /usr/include/eigen3 || echo "Not found"
          echo "Listing /usr/local/include/eigen3:"
          ls /usr/local/include/eigen3 || echo "Not found"

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build manylinux wheels with cibuildwheel
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_BUILD: "yum -y install eigen3-devel || true"
          EIGEN3_INCLUDE_DIR: /usr/include/eigen3
          # Build only CPython versions 3.9 and above.
          CIBW_BUILD: "cp39* cp310* cp311* cp312* cp313*"
          CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-manylinux_i686* cp310-manylinux_i686* cp311-manylinux_i686* cp312-manylinux_i686* cp313-manylinux_i686* cp39-musllinux_* cp310-musllinux_* cp311-musllinux_* cp312-musllinux_* cp313-musllinux_*"
        run: cibuildwheel --output-dir wheelhouse .

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse
          path: wheelhouse

  pypi-publish:
    runs-on: ubuntu-latest
    needs: build_wheels
    permissions:
      id-token: write
    environment:
      name: pypi
    steps:
      - name: Download wheels artifact
        uses: actions/download-artifact@v4
        with:
          name: wheelhouse
          path: wheelhouse

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse
